version: '3'

services:
  nginx:
    image: nginx:1.15.2-alpine
    container_name: net_nginx
    ports:
      - "8083:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
    working_dir: /var/www/Infrastructure/public
    networks:
      bridge:
        ipv4_address: 172.10.1.10

  app:
    build: app
    container_name: net_app
    ports:
      - '9000:9000'
    env_file: ../Infrastructure/.env
    volumes:
      - ../:/var/www
    working_dir: /var/www
    networks:
      bridge:
        ipv4_address: 172.10.1.20

  postgresql:
    container_name: net_pgsql
    image: postgres:15.3
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      bridge:
        ipv4_address: 172.10.1.30

networks:
  bridge:
    driver: bridge
    ipam:
     config:
       - subnet: 172.10.1.0/16
         gateway: 172.10.1.1
